name: deploy

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: 'cd ${{ secrets.SSH_DEPLOY_DIR }} && bash ./cicd/server_deployment_deploy.sh'    
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_USERNAME: "Github Deployments"
        SLACK_TITLE: "salop.emergenciacvp.pt - production"
        SLACK_MESSAGE: "Deployed latest code changes for salop.emergenciacvp.pt. You can access it at https://salop.emergenciacvp.pt"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}